**NumPy**

NumPy is a Python library.

NumPy is short form for 'Numerical Python'.

NumPy is used to work with arrays.

In [19]:
import numpy as np

**array**

A data structure that stores multiple values of same data type under a single variable name.

**Characteristics**

- same data type
- mutable nature
- indexing allowed


In [20]:
arr1=np.array([1, 2, 3, 8, 11, 12, 67])
#print(arr1[2:5])
print(arr1)

[ 1  2  3  8 11 12 67]


**Numpy array attributes**

In Numpy, attributes are properties of arrays that provide information about the array shape,size, datatype, dimension, and so on. There are numerous attributes available, some of these are listed below
:<table border="1" style="border-collapse:collapse;">
<tr>
<th>Attribute</th>
<th>Description</th>
<th>Syntax</th>
</tr>
<tr>
<td>ndim</td>
<td>returns dimension (total number of axes) of the array</td>
<td>arr.ndim</td>
</tr>
<tr>
<td>T</td>
<td>returns transposed array</td>
<td>arr.T</td>
</tr>
<tr>
<td>size</td>
<td>returns number of elements in the array</td>
<td>arr.size</td>
</tr>
<tr>
<td>dtype</td>
<td>returns datatype of elements in the array</td>
<td>arr.dtype</td>
</tr>
<tr>
<td>shape</td>
<td>returns a tuple of sizes of each dimension</td>
<td>arr.shape</td>
</tr>
</table>
e` |
pe` |
arr.shape


In [22]:

arr = np.array([[1,2],[3,4],[1,4]])
arr1 = np.array([[1,2,3,4],[1,2,3,5]])
arr2 = np.array([[[1,2]],[[3,4]]])
print('arr', arr)
print(arr.T)
print('dim:', arr.ndim)
print("size:", arr.size)
print("arrshape:",arr.shape)

print('arr1', arr1)
print("dimension:",arr1.ndim)
print("size:",arr1.size)
print("arr1shap:", arr1.shape)
print(arr2)
print('-------------------')
print(arr2.ndim)
print(arr2)
print(arr2.shape)

arr [[1 2]
 [3 4]
 [1 4]]
[[1 3 1]
 [2 4 4]]
dim: 2
size: 6
arrshape: (3, 2)
arr1 [[1 2 3 4]
 [1 2 3 5]]
dimension: 2
size: 8
arr1shap: (2, 4)
[[[1 2]]

 [[3 4]]]
-------------------
3
[[[1 2]]

 [[3 4]]]
(2, 1, 2)


**Matrix (2D array)**

In [12]:
import numpy as np
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[3, 3, 3], [6, 6, 6], [7, 7, 7]])
print('matrix_a:\n', matrix_a)
print('\n')
print('matrix_b:\n', matrix_b)

matrix_a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix_b:
 [[3 3 3]
 [6 6 6]
 [7 7 7]]


In [15]:
identity_matrix = np.identity(3) # 3x3 identity matrix
zero_matrix = np.zeros((2, 4)) # 2x4 matrix of zeros
print('identity_matrix:\n', identity_matrix)
print('zero_matrix:\n', zero_matrix)

identity_matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
zero_matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
#matrix multiplication
#result_matrix = np.dot(matrix_a, matrix_b)
#OR
result_matrix = matrix_a @ matrix_b
print(result_matrix)

[[ 36  36  36]
 [ 84  84  84]
 [132 132 132]]


In [18]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
C_add = A + B
print("Matrix Addition:\n", C_add)

# Matrix Multiplication (Dot Product)
C_mul = A @ B
print("\nMatrix Multiplication:\n", C_mul)

# Transpose of A
A_transpose = A.T
print("\nTranspose of A:\n", A_transpose)

# Inverse of A
try:
    A_inverse = np.linalg.inv(A)
    print("\nInverse of A:\n", A_inverse)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

Matrix Addition:
 [[ 6  8]
 [10 12]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
